/*
 * generated by Xtext 2.10.0
 */
package org.example.domainmodel.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends XbaseBatchScopeProvider {
}
